### ISSUE TITLE
motion based light control: question/suggestion

### ISSUE THREAD

**Issue by SHxKM** [apollo1220/blueprints#3]
Hi @apollo1220 and thanks for the excellent "Turn on based on motion" blueprint.

Wanted to inquire about the time limit of 300 seconds for the parameter `Turn off wait time (seconds)`:
https://github.com/apollo1220/blueprints/blob/d6539f30ad194d440f15212263b0b2d6077beb17/motion_activated_entity.yaml#L35-L40

Was there any limitation that forced you to cap this `300`? Or was this purely a design-choice? I'm asking because I may need to bump that up to somewhere around `600` but would rather hear from you on why chose that limit, maybe there's something I'm missing..

**Comment by apollo1220** [comment]
The only reason I went with 300 as the cap is because the input gets rendered as a slider in the UI which with higher possible values isn't really usable and I didn't need to go higher personally. You could raise the limit to 600 without causing any issues. If you want you could submit that change and I'll accept that change. With how much adoption that blueprint has seen it probably would be a good idea to make it that much more broadly useful.
