### ISSUE TITLE
more option ?

### ISSUE THREAD

**Issue by Onitsukun** [apollo1220/blueprints#4]
I'm not an expert and I didn't find a solution elsewhere, but is it possible to select a RGB color (and also Brightness) specific to the automation with the motion sensor blueprint? 
For example, I have light in my bedroom activate by motion when someone is standing in the room currently in red dimed light.
I would like to be white during the day. but currently my light only uses the last color setting.

**Comment by apollo1220** [comment]
Not with how I have my blueprint setup. I'm using the homeassistant.turn_on and homeassistant.turn_off services so that it is more generic in it's implementation and you can use lights or standard switches. Due to that, I can't send the light specific options like color and brightness because it just isn't supported by that service. If you want, you can fork it and change it over to specifically calling light.turn_on and light.turn_off and then expose those options for your specific case.
